//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaEmisora.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remesa
    {
        public int idRemesa { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Nombre_Receptor { get; set; }
        public string Correo_Receptor { get; set; }
        public string DPI_Receptor { get; set; }
        public string Estado_Remesa { get; set; }
        public string CodigoSeguridad { get; set; }
        public string fechaEnvio { get; set; }
        public string fechaEntrega { get; set; }
        public Nullable<decimal> MontoUSD { get; set; }
        public Nullable<decimal> MontoQ { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
