//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BancoFinal.EmpresaEmisora {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EmpresaEmisoraSoap", Namespace="http://tempuri.org/")]
    public partial class EmpresaEmisora : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegistrarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarRemesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarRemesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaComisionPorRemesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CodigoSeguridadIdRemesaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarRemesasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaRemesaEspecificaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambioEstadoRemesaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EmpresaEmisora() {
            this.Url = global::BancoFinal.Properties.Settings.Default.BancoFinal_EmpresaEmisora_EmpresaEmisora;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegistrarClienteCompletedEventHandler RegistrarClienteCompleted;
        
        /// <remarks/>
        public event RegistrarRemesaCompletedEventHandler RegistrarRemesaCompleted;
        
        /// <remarks/>
        public event CancelarRemesaCompletedEventHandler CancelarRemesaCompleted;
        
        /// <remarks/>
        public event ConsultaComisionPorRemesaCompletedEventHandler ConsultaComisionPorRemesaCompleted;
        
        /// <remarks/>
        public event CodigoSeguridadIdRemesaCompletedEventHandler CodigoSeguridadIdRemesaCompleted;
        
        /// <remarks/>
        public event ListarRemesasCompletedEventHandler ListarRemesasCompleted;
        
        /// <remarks/>
        public event ConsultaRemesaEspecificaCompletedEventHandler ConsultaRemesaEspecificaCompleted;
        
        /// <remarks/>
        public event CambioEstadoRemesaCompletedEventHandler CambioEstadoRemesaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistrarCliente(string Usuario, string Contrasenia, string NombreCompleto, string DocumentoIdentificacion, string CorreoElectronico, int NoTelefono, string NoCuenta, string TipoCuenta) {
            object[] results = this.Invoke("RegistrarCliente", new object[] {
                        Usuario,
                        Contrasenia,
                        NombreCompleto,
                        DocumentoIdentificacion,
                        CorreoElectronico,
                        NoTelefono,
                        NoCuenta,
                        TipoCuenta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string Usuario, string Contrasenia, string NombreCompleto, string DocumentoIdentificacion, string CorreoElectronico, int NoTelefono, string NoCuenta, string TipoCuenta) {
            this.RegistrarClienteAsync(Usuario, Contrasenia, NombreCompleto, DocumentoIdentificacion, CorreoElectronico, NoTelefono, NoCuenta, TipoCuenta, null);
        }
        
        /// <remarks/>
        public void RegistrarClienteAsync(string Usuario, string Contrasenia, string NombreCompleto, string DocumentoIdentificacion, string CorreoElectronico, int NoTelefono, string NoCuenta, string TipoCuenta, object userState) {
            if ((this.RegistrarClienteOperationCompleted == null)) {
                this.RegistrarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarClienteOperationCompleted);
            }
            this.InvokeAsync("RegistrarCliente", new object[] {
                        Usuario,
                        Contrasenia,
                        NombreCompleto,
                        DocumentoIdentificacion,
                        CorreoElectronico,
                        NoTelefono,
                        NoCuenta,
                        TipoCuenta}, this.RegistrarClienteOperationCompleted, userState);
        }
        
        private void OnRegistrarClienteOperationCompleted(object arg) {
            if ((this.RegistrarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarClienteCompleted(this, new RegistrarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegistrarRemesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistrarRemesa(string Usuario, string Contrasenia, int idClienteEnvia, string NombreReceptor, string CorreoReceptor, string DpiReceptor, decimal MontoUS, string EstadoRemesa) {
            object[] results = this.Invoke("RegistrarRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        idClienteEnvia,
                        NombreReceptor,
                        CorreoReceptor,
                        DpiReceptor,
                        MontoUS,
                        EstadoRemesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarRemesaAsync(string Usuario, string Contrasenia, int idClienteEnvia, string NombreReceptor, string CorreoReceptor, string DpiReceptor, decimal MontoUS, string EstadoRemesa) {
            this.RegistrarRemesaAsync(Usuario, Contrasenia, idClienteEnvia, NombreReceptor, CorreoReceptor, DpiReceptor, MontoUS, EstadoRemesa, null);
        }
        
        /// <remarks/>
        public void RegistrarRemesaAsync(string Usuario, string Contrasenia, int idClienteEnvia, string NombreReceptor, string CorreoReceptor, string DpiReceptor, decimal MontoUS, string EstadoRemesa, object userState) {
            if ((this.RegistrarRemesaOperationCompleted == null)) {
                this.RegistrarRemesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarRemesaOperationCompleted);
            }
            this.InvokeAsync("RegistrarRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        idClienteEnvia,
                        NombreReceptor,
                        CorreoReceptor,
                        DpiReceptor,
                        MontoUS,
                        EstadoRemesa}, this.RegistrarRemesaOperationCompleted, userState);
        }
        
        private void OnRegistrarRemesaOperationCompleted(object arg) {
            if ((this.RegistrarRemesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarRemesaCompleted(this, new RegistrarRemesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CancelarRemesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelarRemesa(string Usuario, string Contrasenia, int IdRemesa) {
            object[] results = this.Invoke("CancelarRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarRemesaAsync(string Usuario, string Contrasenia, int IdRemesa) {
            this.CancelarRemesaAsync(Usuario, Contrasenia, IdRemesa, null);
        }
        
        /// <remarks/>
        public void CancelarRemesaAsync(string Usuario, string Contrasenia, int IdRemesa, object userState) {
            if ((this.CancelarRemesaOperationCompleted == null)) {
                this.CancelarRemesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarRemesaOperationCompleted);
            }
            this.InvokeAsync("CancelarRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa}, this.CancelarRemesaOperationCompleted, userState);
        }
        
        private void OnCancelarRemesaOperationCompleted(object arg) {
            if ((this.CancelarRemesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarRemesaCompleted(this, new CancelarRemesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaComisionPorRemesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaComisionPorRemesa() {
            object[] results = this.Invoke("ConsultaComisionPorRemesa", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaComisionPorRemesaAsync() {
            this.ConsultaComisionPorRemesaAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaComisionPorRemesaAsync(object userState) {
            if ((this.ConsultaComisionPorRemesaOperationCompleted == null)) {
                this.ConsultaComisionPorRemesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaComisionPorRemesaOperationCompleted);
            }
            this.InvokeAsync("ConsultaComisionPorRemesa", new object[0], this.ConsultaComisionPorRemesaOperationCompleted, userState);
        }
        
        private void OnConsultaComisionPorRemesaOperationCompleted(object arg) {
            if ((this.ConsultaComisionPorRemesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaComisionPorRemesaCompleted(this, new ConsultaComisionPorRemesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CodigoSeguridadIdRemesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CodigoSeguridadIdRemesa(string Usuario, string Contrasenia, int IdRemesa, string CodigoSeguridad) {
            object[] results = this.Invoke("CodigoSeguridadIdRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        CodigoSeguridad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CodigoSeguridadIdRemesaAsync(string Usuario, string Contrasenia, int IdRemesa, string CodigoSeguridad) {
            this.CodigoSeguridadIdRemesaAsync(Usuario, Contrasenia, IdRemesa, CodigoSeguridad, null);
        }
        
        /// <remarks/>
        public void CodigoSeguridadIdRemesaAsync(string Usuario, string Contrasenia, int IdRemesa, string CodigoSeguridad, object userState) {
            if ((this.CodigoSeguridadIdRemesaOperationCompleted == null)) {
                this.CodigoSeguridadIdRemesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodigoSeguridadIdRemesaOperationCompleted);
            }
            this.InvokeAsync("CodigoSeguridadIdRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        CodigoSeguridad}, this.CodigoSeguridadIdRemesaOperationCompleted, userState);
        }
        
        private void OnCodigoSeguridadIdRemesaOperationCompleted(object arg) {
            if ((this.CodigoSeguridadIdRemesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CodigoSeguridadIdRemesaCompleted(this, new CodigoSeguridadIdRemesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarRemesas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListarRemesas(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega) {
            object[] results = this.Invoke("ListarRemesas", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        NombreCompletoEmisor,
                        NombreCompletoReceptor,
                        MontoQ,
                        MontoUS,
                        FechaEnvio,
                        FechaEntrega});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarRemesasAsync(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega) {
            this.ListarRemesasAsync(Usuario, Contrasenia, IdRemesa, NombreCompletoEmisor, NombreCompletoReceptor, MontoQ, MontoUS, FechaEnvio, FechaEntrega, null);
        }
        
        /// <remarks/>
        public void ListarRemesasAsync(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega, object userState) {
            if ((this.ListarRemesasOperationCompleted == null)) {
                this.ListarRemesasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarRemesasOperationCompleted);
            }
            this.InvokeAsync("ListarRemesas", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        NombreCompletoEmisor,
                        NombreCompletoReceptor,
                        MontoQ,
                        MontoUS,
                        FechaEnvio,
                        FechaEntrega}, this.ListarRemesasOperationCompleted, userState);
        }
        
        private void OnListarRemesasOperationCompleted(object arg) {
            if ((this.ListarRemesasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarRemesasCompleted(this, new ListarRemesasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultaRemesaEspecifica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultaRemesaEspecifica(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega) {
            object[] results = this.Invoke("ConsultaRemesaEspecifica", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        NombreCompletoEmisor,
                        NombreCompletoReceptor,
                        MontoQ,
                        MontoUS,
                        FechaEnvio,
                        FechaEntrega});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaRemesaEspecificaAsync(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega) {
            this.ConsultaRemesaEspecificaAsync(Usuario, Contrasenia, IdRemesa, NombreCompletoEmisor, NombreCompletoReceptor, MontoQ, MontoUS, FechaEnvio, FechaEntrega, null);
        }
        
        /// <remarks/>
        public void ConsultaRemesaEspecificaAsync(string Usuario, string Contrasenia, int IdRemesa, string NombreCompletoEmisor, string NombreCompletoReceptor, string MontoQ, string MontoUS, string FechaEnvio, string FechaEntrega, object userState) {
            if ((this.ConsultaRemesaEspecificaOperationCompleted == null)) {
                this.ConsultaRemesaEspecificaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaRemesaEspecificaOperationCompleted);
            }
            this.InvokeAsync("ConsultaRemesaEspecifica", new object[] {
                        Usuario,
                        Contrasenia,
                        IdRemesa,
                        NombreCompletoEmisor,
                        NombreCompletoReceptor,
                        MontoQ,
                        MontoUS,
                        FechaEnvio,
                        FechaEntrega}, this.ConsultaRemesaEspecificaOperationCompleted, userState);
        }
        
        private void OnConsultaRemesaEspecificaOperationCompleted(object arg) {
            if ((this.ConsultaRemesaEspecificaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaRemesaEspecificaCompleted(this, new ConsultaRemesaEspecificaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambioEstadoRemesa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CambioEstadoRemesa(string Usuario, string Contrasenia, int IdBancoReceptor, int IdRemesa, string NuevoEstadoRemesa) {
            object[] results = this.Invoke("CambioEstadoRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdBancoReceptor,
                        IdRemesa,
                        NuevoEstadoRemesa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CambioEstadoRemesaAsync(string Usuario, string Contrasenia, int IdBancoReceptor, int IdRemesa, string NuevoEstadoRemesa) {
            this.CambioEstadoRemesaAsync(Usuario, Contrasenia, IdBancoReceptor, IdRemesa, NuevoEstadoRemesa, null);
        }
        
        /// <remarks/>
        public void CambioEstadoRemesaAsync(string Usuario, string Contrasenia, int IdBancoReceptor, int IdRemesa, string NuevoEstadoRemesa, object userState) {
            if ((this.CambioEstadoRemesaOperationCompleted == null)) {
                this.CambioEstadoRemesaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambioEstadoRemesaOperationCompleted);
            }
            this.InvokeAsync("CambioEstadoRemesa", new object[] {
                        Usuario,
                        Contrasenia,
                        IdBancoReceptor,
                        IdRemesa,
                        NuevoEstadoRemesa}, this.CambioEstadoRemesaOperationCompleted, userState);
        }
        
        private void OnCambioEstadoRemesaOperationCompleted(object arg) {
            if ((this.CambioEstadoRemesaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambioEstadoRemesaCompleted(this, new CambioEstadoRemesaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistrarClienteCompletedEventHandler(object sender, RegistrarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void RegistrarRemesaCompletedEventHandler(object sender, RegistrarRemesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarRemesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarRemesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CancelarRemesaCompletedEventHandler(object sender, CancelarRemesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarRemesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarRemesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultaComisionPorRemesaCompletedEventHandler(object sender, ConsultaComisionPorRemesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaComisionPorRemesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaComisionPorRemesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CodigoSeguridadIdRemesaCompletedEventHandler(object sender, CodigoSeguridadIdRemesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CodigoSeguridadIdRemesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CodigoSeguridadIdRemesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ListarRemesasCompletedEventHandler(object sender, ListarRemesasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarRemesasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarRemesasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ConsultaRemesaEspecificaCompletedEventHandler(object sender, ConsultaRemesaEspecificaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaRemesaEspecificaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaRemesaEspecificaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CambioEstadoRemesaCompletedEventHandler(object sender, CambioEstadoRemesaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CambioEstadoRemesaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CambioEstadoRemesaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591