//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banguat.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanguatEntities : DbContext
    {
        public BanguatEntities()
            : base("name=BanguatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TasaCambio> TasaCambio { get; set; }
        public virtual DbSet<Monto> Monto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
