//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banguat.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monto
    {
        public int idMinMax { get; set; }
        public Nullable<int> montoMin { get; set; }
        public Nullable<int> montoMax { get; set; }
        public string fecha { get; set; }
    }
}
