//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace EmpresaEmisora.BDEmpresaEmisora {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BDEmpresaEmisoraSoap", Namespace="http://tempuri.org/")]
    public partial class BDEmpresaEmisora : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback insertarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BDEmpresaEmisora() {
            this.Url = global::EmpresaEmisora.Properties.Settings.Default.EmpresaEmisora_BDEmpresaEmisora_BDEmpresaEmisora;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event insertarClienteCompletedEventHandler insertarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string insertarCliente(string usuario, string pass, string nombre, string documento_identificacion, string correo_electronico, int no_telefono, string no_cuenta, string tipo_cuenta) {
            object[] results = this.Invoke("insertarCliente", new object[] {
                        usuario,
                        pass,
                        nombre,
                        documento_identificacion,
                        correo_electronico,
                        no_telefono,
                        no_cuenta,
                        tipo_cuenta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void insertarClienteAsync(string usuario, string pass, string nombre, string documento_identificacion, string correo_electronico, int no_telefono, string no_cuenta, string tipo_cuenta) {
            this.insertarClienteAsync(usuario, pass, nombre, documento_identificacion, correo_electronico, no_telefono, no_cuenta, tipo_cuenta, null);
        }
        
        /// <remarks/>
        public void insertarClienteAsync(string usuario, string pass, string nombre, string documento_identificacion, string correo_electronico, int no_telefono, string no_cuenta, string tipo_cuenta, object userState) {
            if ((this.insertarClienteOperationCompleted == null)) {
                this.insertarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarClienteOperationCompleted);
            }
            this.InvokeAsync("insertarCliente", new object[] {
                        usuario,
                        pass,
                        nombre,
                        documento_identificacion,
                        correo_electronico,
                        no_telefono,
                        no_cuenta,
                        tipo_cuenta}, this.insertarClienteOperationCompleted, userState);
        }
        
        private void OninsertarClienteOperationCompleted(object arg) {
            if ((this.insertarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarClienteCompleted(this, new insertarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void insertarClienteCompletedEventHandler(object sender, insertarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591