//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IVE.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remesa
    {
        public int Id { get; set; }
        public int ID_Remesa { get; set; }
        public decimal Monto { get; set; }
        public string Nombre_Emisor { get; set; }
        public string Correo_Emisor { get; set; }
        public string Doc_Identificacion_Emisor { get; set; }
        public string Direccion_Emisor { get; set; }
        public int No_Telefono_Emisor { get; set; }
        public string Nombre_Receptor { get; set; }
        public string Correo_Receptor { get; set; }
        public string Doc_Identificacion_Receptor { get; set; }
        public string Direccion_Receptor { get; set; }
        public int No_Telefono_Receptor { get; set; }
        public string Fecha_Recepcion_Remesa { get; set; }
    }
}
